apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  namespace: default
  labels:
    app: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: devops-demo
        image: MOHIT042005/devops-demo:v1
        ports:
        - containerPort: 80